---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


##1. Loading and preprocessing the data
```{R}
activityFile <- ".\\activity\\activity.csv"
activitydf <- read.csv(activityFile) 
```
preview contents of file
```{R}
head(activitydf)
tail(activitydf)
activitydf[activitydf$date=='2012-10-31',]$steps
activitydf[activitydf$interval==1005,]$steps
```

##2.Histogram of the total number of steps taken each day

I will use the base plotting system and increase the number of breaks in the data
```{R}
activityTotbyDate <- aggregate(steps ~ date, data=activitydf, sum)
hist(activityTotbyDate$steps, col="blue", main="", xlab="", breaks=20) 
title(xlab="Total Steps per Day", main="Histogram of Total Steps per Day")
```


##3. What is mean total number of steps taken per day?

I will show both the mean and the median
```{R}
mean(activityTotbyDate$steps)
median(activityTotbyDate$steps)
```


## What is the average daily activity pattern?

4.Time series plot of the average number of steps taken

Again, use the base plotting system. This plot will have the NA values omitted
```{R}
activityMeanbyInterval <- 
      aggregate(steps ~ interval, data=activitydf, mean, na.action = na.omit)
plot(steps ~ interval, data=activityMeanbyInterval, type="l", xlab="", ylab="")
title(xlab="5-minute interval", ylab="Average steps (all dates)")
```

5.Display the 5-minute interval that, on average, contains the maximum number of steps
```{R}
activityMeanbyInterval[which.max(activityMeanbyInterval$steps),]
```

## Imputing missing values

The first thing to notice is the the only missing values are for complete days in the dataset and that only steps are missing.

```{R}
#create dataset for missing values
missingValues <- activitydf[is.na(activitydf),]

#show number of missing values in the dataset
nrow(missingValues)

#show dates with missing values
unique(as.Date(missingValues[,"date"]))
```

For missing values in the dataset, I will use the mean per 5-minute interval across all days for each interval in the missing days.

```{R}
#combine missingvalues dataframe with the Mean value for each 5 minute interval
meanForNA <- merge(missingValues[,c("date", "interval")], activityMeanbyInterval, by="interval")
rm(missingValues) ##clean-up
```

create a new dataset to fill in missing data using mean for the 5 minute interval

```{R}
#combine activitydf, removing NA's, with the new dataframe using the interval Mean values
activitydfMeanForNA <- rbind(
        activitydf[complete.cases(activitydf),], 
        meanForNA[,c("steps","date","interval")])
rm(meanForNA) ##clean-up
#sort list
activitydfMeanForNA <- activitydfMeanForNA[order(activitydfMeanForNA$date, activitydfMeanForNA$interval),]
```

#7.Histogram of the total number of steps taken each day after missing values are imputed

First Calculate the total number of steps taken per day
```{R}
activityTotbyDate <- aggregate(steps ~ date, data=activitydfMeanForNA, sum)
```

Show the histogram
```{R}
hist(activityTotbyDate$steps, col="green", main="", xlab="", breaks=20) 
title(xlab="Total Steps per Day", main="Histogram of Total Steps per Day")
```

## Are there differences in activity patterns between weekdays and weekends?

8.Panel plot comparing the average number of steps taken per 5-minute interval 
across weekdays and weekends

First add a column to the dataset with a weekday, weekend factor

```{R}
#Setup weekend and workday array
weekendDays <- c("Saturday", "Sunday")
workDays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")

#Create ordered factor for weekday/weekend
dayType <- factor(c("weekday", "weekend"),ordered = TRUE)

#Create aggregate dataframes for weekend and weekdays.  
#Aggregate separately and use rbind to combine. Use cbind 
#to append weekday/weekend factor
activitydfMeanForNA <- rbind(
      cbind(aggregate(steps ~ interval, 
                  data=activitydfMeanForNA[weekdays(as.Date(activitydfMeanForNA$date)) %in% workDays,], 
                  mean), weekday=dayType[1] 
        ),
      cbind(aggregate(steps ~ interval, 
                data=activitydfMeanForNA[weekdays(as.Date(activitydfMeanForNA$date)) %in% weekendDays,], 
                mean), weekday=dayType[2]
        )
    )
```

Create panel plot. I used the base plotting system and tried to customize it, hence the extra code.

```{R}
par(mfrow = c(2, 1))   #set plots per page
par(mar = c(0,0,0,0))  #set plot margins 
par(oma = c(5,5,1,1))  #set outer margins
par(mgp=c(2,0.6,0))
par(cex=0.6)
par(tcl=-0.25) #set tick length

#plot weekdays
plot(steps ~ interval, 
      data=activitydfMeanForNA[activitydfMeanForNA$weekday=="weekday",], 
      type="l", col="red", ylim=c(0,250), ann=FALSE, xaxt="n")
mtext("Weekdays", col="red", side = 3, line = -1.5, adj = 0.1, cex = 0.7)

#plot weekends
plot(steps ~ interval, 
     data=activitydfMeanForNA[activitydfMeanForNA$weekday=="weekend",], 
     type="l", col="blue", ylim=c(0,250),  ann=FALSE)
mtext("Weekends", col="blue", side = 3, line = -1.5, adj = 0.1, cex = 0.7)

mtext("5-minute interval", side = 1, cex=0.7, outer = TRUE, line = 2.2)
mtext("Average steps", side = 2, cex=0.7, outer = TRUE, line = 2.2)
```

There are differences in the pattern between weekends and weekdays as shown above


